# Увеличиваем память, доступную Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA пока не полностью совместима с configuration cache, см.:
# https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric-свойства
# Актуальные версии проверяются на https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Свойства мода
version=1.0.0
group=com.errormod

# Зависимости
fabric_api_version=0.161.0+26.3
